SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    (C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
    )
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;