SELECT CH.CAR_ID,
       ROUND(AVG(CH.AD), 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID,
           DATEDIFF(END_DATE, START_DATE)+1 AS AD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) CH
GROUP BY CH.CAR_ID
HAVING ROUND(AVG(CH.AD),1) >= 7
ORDER BY AVERAGE_DURATION DESC, CH.CAR_ID DESC;